schema_version = 1
agent_id = "tester_agent"
module = "tester_agent"

container_capabilities = [
  "network",
  "shared_volume",
]

application_capabilities = [
  "a2a",
  "code_execution",
  "mcp_client",
  "openai_agents",
]

[squid_proxy]
allowed_domains = []
allowed_ip_addresses = []

[mcp_sidecar]
tools = [
  "run_python_script",
]
resources = []
