schema_version = 1
agent_id = "agent_1"
module = "sandbox_agent"

container_capabilities = [
  "network",
  "shared_volume",
]

application_capabilities = [
  "a2a",
  "openai_agents",
]

[squid_proxy]
allowed_domains = []
allowed_ip_addresses = []

[mcp_sidecar]
tools = []
resources = []
